# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProofs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'proof_images')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(default=b'', max_length=100, unique=True)),
                ('bank_name', models.CharField(choices=[(b'Access Bank', b'Access Bank'), (b'Citibank', b'Citibank'), (b'Diamond Bank', b'Diamond Bank'), (b'Ecobank', b'Ecobank'), (b'Fidelity Bank', b'Fidelity Bank'), (b'First Bank', b'First Bank'), (b'First City Monument Bank (FCMB)', b'First City Monument Bank (FCMB)'), (b'FSDH Merchant Bank', b'FSDH Merchant Bank'), (b'Guarantee Trust Bank (GTB)', b'Guarantee Trust Bank (GTB)'), (b'Heritage Bank', b'Heritage Bank'), (b'Keystone Bank', b'Keystone Bank'), (b'Rand Merchant Bank', b'Rand Merchant Bank'), (b'Skye Bank', b'Skye Bank'), (b'Stanbic IBTC Bank', b'Stanbic IBTC Bank'), (b'Standard Chartered Bank', b'Standard Chartered Bank'), (b'Sterling Bank', b'Sterling Bank'), (b'Suntrust Bank', b'Suntrust Bank'), (b'Union Bank', b'Union Bank'), (b'United Bank for Africa (UBA)', b'United Bank for Africa (UBA)'), (b'Unity Bank', b'Unity Bank'), (b'Wema Bank', b'Wema Bank'), (b'Zenith Bank', b'Zenith Bank')], default=b'', max_length=80)),
                ('account_number', models.CharField(default=b'', max_length=10, unique=True)),
                ('account_type', models.CharField(choices=[(b'Savings', b'Savings'), (b'Current', b'Current'), (b'Credit', b'Credit'), (b'Others', b'Others')], default=b'', max_length=20)),
                ('plan_type', models.CharField(default=b'', max_length=20)),
                ('confirm1', models.IntegerField(default=0)),
                ('confirm2', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('picture', models.ImageField(blank=True, upload_to=b'profile_images')),
                ('picture_height', models.PositiveIntegerField(blank=True, default=b'200', editable=False, null=True)),
                ('picture_width', models.PositiveIntegerField(blank=True, default=b'200', editable=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
